name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test case 1
      id: test-case-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test case 1
        setup-command: ''
        command: make check-1
        timeout: 10
        max-score: 1
    - name: test case 2
      id: test-case-2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test case 2
        setup-command: ''
        command: make check-2
        timeout: 10
        max-score: 1
    - name: test case 3
      id: test-case-3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test case 3
        setup-command: ''
        command: make check-3
        timeout: 10
        max-score: 1
    - name: test case 4
      id: test-case-4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test case 4
        setup-command: ''
        command: make check-4
        timeout: 10
        max-score: 1
    - name: test case 5
      id: test-case-5
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test case 5
        setup-command: ''
        command: make check-5
        timeout: 10
        max-score: 1
    - name: test case 6
      id: test-case-6
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test case 6
        setup-command: ''
        command: make check-6
        timeout: 10
        max-score: 1
    - name: test case 7
      id: test-case-7
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test case 7
        setup-command: ''
        command: make check-7
        timeout: 10
        max-score: 1
    - name: test case 8
      id: test-case-8
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test case 8
        setup-command: ''
        command: make check-8
        timeout: 10
        max-score: 1
    - name: test case 9
      id: test-case-9
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test case 9
        setup-command: ''
        command: make check-9
        timeout: 10
        max-score: 1
    - name: test case 10
      id: test-case-10
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test case 10
        setup-command: ''
        command: make check-10
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-CASE-1_RESULTS: "${{steps.test-case-1.outputs.result}}"
        TEST-CASE-2_RESULTS: "${{steps.test-case-2.outputs.result}}"
        TEST-CASE-3_RESULTS: "${{steps.test-case-3.outputs.result}}"
        TEST-CASE-4_RESULTS: "${{steps.test-case-4.outputs.result}}"
        TEST-CASE-5_RESULTS: "${{steps.test-case-5.outputs.result}}"
        TEST-CASE-6_RESULTS: "${{steps.test-case-6.outputs.result}}"
        TEST-CASE-7_RESULTS: "${{steps.test-case-7.outputs.result}}"
        TEST-CASE-8_RESULTS: "${{steps.test-case-8.outputs.result}}"
        TEST-CASE-9_RESULTS: "${{steps.test-case-9.outputs.result}}"
        TEST-CASE-10_RESULTS: "${{steps.test-case-10.outputs.result}}"
      with:
        runners: test-case-1,test-case-2,test-case-3,test-case-4,test-case-5,test-case-6,test-case-7,test-case-8,test-case-9,test-case-10